image: Visual Studio 2022

init:
  - cmd: set PATH=C:\Python310;C:\Python310\Scripts;%PATH%

build_script:
  - cmd: pip install selenium pyinstaller
  - cmd: pyinstaller --onefile --noconsole stock_monitor.py

artifacts:
  - path: dist\*.exe
    name: StockMonitor